const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Mouse,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.video.Acts.Play,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.video.Exps.PlaybackTime,
		C3.Plugins.video.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{maskBg: 0},
	{zoomGosterge: 0},
	{hucre: 0},
	{maskFrame: 0},
	{bg: 0},
	{hucreBg: 0},
	{Audio: 0},
	{masa: 0},
	{Fade: 0},
	{Video3: 0},
	{Video4: 0},
	{beher: 0},
	{posX: 0},
	{posY: 0},
	{DragDrop: 0},
	{cubuk: 0},
	{popup: 0},
	{videoBg: 0},
	{Sprite2: 0},
	{metin: 0},
	{Video1: 0},
	{Video2: 0},
	{gölge2: 0},
	{tup2: 0},
	{damla: 0},
	{tüpönalt2: 0},
	{tüpönüst2: 0},
	{maskFrame2: 0},
	{damlalıkSıvı: 0},
	{popup2: 0},
	{tepkimeText2: 0},
	{tüparka2: 0},
	{damlalik: 0},
	{üçayak2: 0},
	{zoomGosterge2: 0},
	{orbital: 0},
	{maskBg2: 0},
	{hucreBg2: 0},
	{masa2: 0},
	{Başlıksız: 0},
	{Başlıksız2: 0},
	{Başlıksız3: 0},
	{gameIndex: 0},
	{frame: 0},
	{Mouse: 0},
	{homeBtn: 0},
	{popup3: 0},
	{maskBg3: 0},
	{zoomGosterge3: 0},
	{vana: 0},
	{tepkimeBar: 0},
	{tepkimeBarText: 0},
	{detailID: 0},
	{clicked: 0},
	{active: 0},
	{detailBtn: 0},
	{zoom2Gosterge3: 0},
	{detailBtn2: 0},
	{hucreBg3: 0},
	{hucreBg4: 0},
	{kapak: 0},
	{detail: 0},
	{cubukControl: 0},
	{beherControl: 0},
	{isLoader: 0},
	{timeCount: 0},
	{tersControl: 0},
	{firstControl: 0},
	{damlaControl: 0},
	{timeStart: 0},
	{damlalikControl: 0},
	{tupControl: 0},
	{damlaStart: 0},
	{timeCount2: 0},
	{tersControl2: 0},
	{firstControl2: 0},
	{timeStart2: 0},
	{vanaControl: 0},
	{detailControl: 0},
	{tupControl2: 0},
	{damlaStart2: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	maskBg: class extends self.ISpriteInstance {},
	zoomGosterge: class extends self.ISpriteInstance {},
	hucre: class extends self.ISpriteInstance {},
	maskFrame: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	hucreBg: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	masa: class extends self.ISpriteInstance {},
	Video3: class extends self.IWorldInstance {},
	Video4: class extends self.IWorldInstance {},
	beher: class extends self.ISpriteInstance {},
	cubuk: class extends self.ISpriteInstance {},
	popup: class extends self.ISpriteInstance {},
	videoBg: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	metin: class extends self.ISpriteInstance {},
	Video1: class extends self.IWorldInstance {},
	Video2: class extends self.IWorldInstance {},
	gölge2: class extends self.ISpriteInstance {},
	tup2: class extends self.ISpriteInstance {},
	damla: class extends self.ISpriteInstance {},
	tüpönalt2: class extends self.ISpriteInstance {},
	tüpönüst2: class extends self.ISpriteInstance {},
	maskFrame2: class extends self.ISpriteInstance {},
	damlalıkSıvı: class extends self.ISpriteInstance {},
	popup2: class extends self.ISpriteInstance {},
	tepkimeText2: class extends self.ISpriteInstance {},
	tüparka2: class extends self.ISpriteInstance {},
	damlalik: class extends self.ISpriteInstance {},
	üçayak2: class extends self.ISpriteInstance {},
	zoomGosterge2: class extends self.ISpriteInstance {},
	orbital: class extends self.ISpriteInstance {},
	maskBg2: class extends self.ISpriteInstance {},
	hucreBg2: class extends self.ISpriteInstance {},
	masa2: class extends self.ISpriteInstance {},
	Başlıksız: class extends self.ISpriteInstance {},
	Başlıksız2: class extends self.ISpriteInstance {},
	Başlıksız3: class extends self.ISpriteInstance {},
	frame: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	homeBtn: class extends self.ISpriteInstance {},
	popup3: class extends self.ISpriteInstance {},
	maskBg3: class extends self.ISpriteInstance {},
	zoomGosterge3: class extends self.ISpriteInstance {},
	vana: class extends self.ISpriteInstance {},
	tepkimeBar: class extends self.ISpriteInstance {},
	tepkimeBarText: class extends self.ISpriteInstance {},
	detailBtn: class extends self.ISpriteInstance {},
	zoom2Gosterge3: class extends self.ISpriteInstance {},
	detailBtn2: class extends self.ISpriteInstance {},
	hucreBg3: class extends self.ISpriteInstance {},
	hucreBg4: class extends self.ISpriteInstance {},
	kapak: class extends self.ISpriteInstance {},
	detail: class extends self.ISpriteInstance {}
}