const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.video.Exps.PlaybackTime,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Acts.SetOpacity,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{maskBg: 0},
	{zoomGosterge: 0},
	{mercekAlt: 0},
	{hucre: 0},
	{maskFrame: 0},
	{bg: 0},
	{hucreBg: 0},
	{Audio: 0},
	{masa: 0},
	{Video1: 0},
	{Video2: 0},
	{gölge: 0},
	{üçayak: 0},
	{tüpönalt: 0},
	{tüpönüst: 0},
	{tüparka: 0},
	{tup: 0},
	{damla: 0},
	{posX: 0},
	{posY: 0},
	{DragDrop: 0},
	{damlalik: 0},
	{damlalıkSıvı: 0},
	{timeCount: 0},
	{tersControl: 0},
	{firstControl: 0},
	{damlaControl: 0},
	{timeStart: 0},
	{damlalikControl: 0},
	{tupControl: 0},
	{damlaStart: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	maskBg: class extends self.ISpriteInstance {},
	zoomGosterge: class extends self.ISpriteInstance {},
	mercekAlt: class extends self.ISpriteInstance {},
	hucre: class extends self.ISpriteInstance {},
	maskFrame: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	hucreBg: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	masa: class extends self.ISpriteInstance {},
	Video1: class extends self.IWorldInstance {},
	Video2: class extends self.IWorldInstance {},
	gölge: class extends self.ISpriteInstance {},
	üçayak: class extends self.ISpriteInstance {},
	tüpönalt: class extends self.ISpriteInstance {},
	tüpönüst: class extends self.ISpriteInstance {},
	tüparka: class extends self.ISpriteInstance {},
	tup: class extends self.ISpriteInstance {},
	damla: class extends self.ISpriteInstance {},
	damlalik: class extends self.ISpriteInstance {},
	damlalıkSıvı: class extends self.ISpriteInstance {}
}